### ISSUE TITLE
Peer-to-peer code review exercise (Week 3, Module 2)

### ISSUE THREAD

**Issue by Daphineatim** [TechnoAndy/To-Do-List-Review#2]
Hi @TechnoAndy ,

Good job so far!👍

### Highlights
The app successfully updates the local storage when I mark a todo item as completed 👏
Linters are passing 👏
README is descriptive 👏
DRY 👍
Pretty clean code. 👍 💯
JavaScript Best practice 👍 💯
I have nothing to add on , rather saying congratulation for that best Job.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

**Comment by TechnoAndy** [comment]
Thank you for your feedback
